### ISSUE TITLE
Big files

### ISSUE THREAD

**Issue by VolBog** [dwaithe/FCS_point_correlator#13]
I have the question about big files in the FCS program.
Usually I work with file size around 200 Mb or more.
When I import the file around 100Mb python use around 5Gb of ram. And usually have crashes. 
Sometimes I have to correlate files around 2Gb.

I have question about program optimization. Can we do it? 

Like put the parameter: work with file in parts by 50Mb.

Thank you

**Comment by VolBog** [comment]
I checked the small files.
The 300kb file use the 1-4Gb of RAM.
Its normal behavior or I must switch my OS to Linux?

[default.zip](https://github.com/dwaithe/FCS_point_correlator/files/3443954/default.zip)

**Comment by dwaithe** [comment]
Sorry for not answering this before. The best way of dealing with data this big, would be to bin the data beforehand and correlate it with a multiple tau algorithm. This would reduce the size in memory significantly. You could still do photon counting statistics on the raw trace, but you would do this by processing the photons in series rather than altogether, which is required for the correlation. Hope that helps. Maybe you solved the problem already 2 years ago :-).
